export { BovinosFilters } from "./BovinosFilters";
export { BovinoList } from "./BovinoList";
export { BovinoDetail } from "./BovinoDetail";
export { SanitarioBadge } from "./SanitarioBadge";
export { PruebaStatusBadge } from "./PruebaStatusBadge";
export { ExportableCheckBadge } from "./ExportableCheckBadge";
export { useBovinos } from "./hooks/useBovinos";
export { useBovinoDetail } from "./hooks/useBovinoDetail";
export type { BovinoDetailTab } from "./hooks/useBovinoDetail";
export type { BovinosFiltersState } from "@/modules/bovinos/domain/entities/Bovino";
